// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	ReqSignup
	RespSignup
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqSignup struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *ReqSignup) Reset()                    { *m = ReqSignup{} }
func (m *ReqSignup) String() string            { return proto1.CompactTextString(m) }
func (*ReqSignup) ProtoMessage()               {}
func (*ReqSignup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqSignup) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqSignup) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RespSignup struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RespSignup) Reset()                    { *m = RespSignup{} }
func (m *RespSignup) String() string            { return proto1.CompactTextString(m) }
func (*RespSignup) ProtoMessage()               {}
func (*RespSignup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RespSignup) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RespSignup) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*ReqSignup)(nil), "proto.ReqSignup")
	proto1.RegisterType((*RespSignup)(nil), "proto.RespSignup")
}

func init() { proto1.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xce, 0x5c, 0x9c, 0x41, 0xa9,
	0x85, 0xc1, 0x99, 0xe9, 0x79, 0xa5, 0x05, 0x42, 0x52, 0x5c, 0x1c, 0x20, 0x15, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8,
	0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b, 0x59, 0x71, 0x71, 0x05, 0xa5, 0x16,
	0x17, 0x40, 0x4d, 0x11, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x81, 0x98, 0xc0, 0x1a, 0x04, 0x66, 0x0b,
	0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x42, 0x35, 0xc3, 0xb8, 0x46, 0x4e,
	0x5c, 0xdc, 0xa1, 0xc5, 0xa9, 0x45, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xc6, 0x5c,
	0x5c, 0x60, 0x2e, 0xc4, 0x28, 0x01, 0x88, 0x63, 0xf5, 0xe0, 0x4e, 0x94, 0x12, 0x84, 0x8b, 0xc0,
	0xec, 0x53, 0x62, 0x48, 0x62, 0x03, 0x8b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xad,
	0xc6, 0x09, 0xe0, 0x00, 0x00, 0x00,
}
